function replaceModel()
txd = engineLoadTXD('a8s8.txd',440)
engineImportTXD(txd,440)
dff = engineLoadDFF('a8s8.dff',440)
engineReplaceModel(dff,440)
txd = engineLoadTXD('amg_one.txd',503)
engineImportTXD(txd,503)
dff = engineLoadDFF('amg_one.dff',503)
engineReplaceModel(dff,503)
txd = engineLoadTXD('avtr.txd',517)
engineImportTXD(txd,517)
dff = engineLoadDFF('avtr.dff',517)
engineReplaceModel(dff,517)
txd = engineLoadTXD('ben_cont.txd',518)
engineImportTXD(txd,518)
dff = engineLoadDFF('ben_cont.dff',518)
engineReplaceModel(dff,518)
txd = engineLoadTXD('chiron.txd',506)
engineImportTXD(txd,506)
dff = engineLoadDFF('chiron.dff',506)
engineReplaceModel(dff,506)
txd = engineLoadTXD('e38.txd',534)
engineImportTXD(txd,534)
dff = engineLoadDFF('e38.dff',534)
engineReplaceModel(dff,534)
txd = engineLoadTXD('e39.txd',580)
engineImportTXD(txd,580)
dff = engineLoadDFF('e39.dff',580)
engineReplaceModel(dff,580)
txd = engineLoadTXD('aventador.txd',542)
engineImportTXD(txd,542)
dff = engineLoadDFF('aventador.dff',542)
engineReplaceModel(dff,542)
txd = engineLoadTXD('huracan.txd',600)
engineImportTXD(txd,600)
dff = engineLoadDFF('huracan.dff',600)
engineReplaceModel(dff,600)
txd = engineLoadTXD('m2.txd',602)
engineImportTXD(txd,602)
dff = engineLoadDFF('m2.dff',602)
engineReplaceModel(dff,602)
txd = engineLoadTXD('x72023.txd',418)
engineImportTXD(txd,418)
dff = engineLoadDFF('x72023.dff',418)
engineReplaceModel(dff,418)
txd = engineLoadTXD('divo.txd',436)
engineImportTXD(txd,436)
dff = engineLoadDFF('divo.dff',436)
engineReplaceModel(dff,436)
end
addEventHandler ( 'onClientResourceStart', getResourceRootElement(getThisResource()), replaceModel)
addCommandHandler ( 'reloadcar', replaceModel )