
--addEventHandler("onResourceStart", resourceRoot, function()
--	local mapsToSetAllDimensions = {
--		"redring.map",
--	}
--	for _, mapName in ipairs(mapsToSetAllDimensions) do
--		for _, element in ipairs(getElementsByType("object", getResourceMapRootElement(resource, mapName))) do
--			setElementDimension(element, -1)
--		end
--	end
--end)
