addCommandHandler("pos",function() 
	local x,y,z = getElementPosition(localPlayer)
	outputConsole("{"..x..","..y..","..z.."}")
	setClipboard("{"..x..","..y..","..z.."}")
	local xc, yc, zc, lxc, lyc, lzc = getCameraMatrix ()
	local xc,yc,zc,lxc,lyc,lzc = getCameraMatrix(localPlayer)
	outputConsole("{"..xc..","..yc..","..zc..","..lxc..","..lyc..","..lzc.."}")
	setClipboard("{"..xc..","..yc..","..zc..","..lxc..","..lyc..","..lzc.."}")
end)